// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportCSV'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDefaultPaperSize() {
  return window['go']['main']['App']['GetDefaultPaperSize']();
}

export function GetDefaultTagLayout() {
  return window['go']['main']['App']['GetDefaultTagLayout']();
}

export function GetDefaultTagTemplate() {
  return window['go']['main']['App']['GetDefaultTagTemplate']();
}

export function GetSystemFonts() {
  return window['go']['main']['App']['GetSystemFonts']();
}

export function ImportCSV() {
  return window['go']['main']['App']['ImportCSV']();
}

export function LoadProject() {
  return window['go']['main']['App']['LoadProject']();
}

export function SavePDF(arg1) {
  return window['go']['main']['App']['SavePDF'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SelectBackgroundImage() {
  return window['go']['main']['App']['SelectBackgroundImage']();
}
