// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {utils} from '../models';

export function ExportCSV(arg1:Array<string>,arg2:Array<any>):Promise<string>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetDefaultPaperSize():Promise<models.PaperSize>;

export function GetDefaultTagLayout():Promise<models.TagLayout>;

export function GetDefaultTagTemplate():Promise<models.TagTemplate>;

export function GetSystemFonts():Promise<Array<utils.FontInfo>>;

export function ImportCSV():Promise<models.CSVResult>;

export function LoadProject():Promise<models.ProjectData>;

export function SavePDF(arg1:models.ProjectData):Promise<string>;

export function SaveProject(arg1:models.ProjectData):Promise<string>;

export function SelectBackgroundImage():Promise<string>;
